spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
#spring.datasource.driver-class-name: org.postgresql.Driver

#logging.level.root=INFO
#logging.level.com.example=DEBUG
#logging.file.name=loggers.log
#logging.pattern.file=%d{yyy-MM-dd} [%level] %c{1.} [%t] %m%n